# Generated by Django 5.0.2 on 2024-03-06 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ('position',), 'verbose_name_plural': 'Project Categories'},
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='position',
            field=models.SmallIntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('slug', models.SlugField(max_length=75)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='projects/')),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.SmallIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='home.projectcategory')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ('position',),
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('position', 'category'), name='unique_position_per_each_category'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('id', 'slug')},
        ),
    ]
