# Generated by Django 5.0.2 on 2024-03-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_projectcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='unique_position_per_each_category',
        ),
    ]
