# Generated by Django 5.0.2 on 2024-03-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_reservation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='Message',
        ),
    ]
